name = "RaBitQ"
uuid = "7efa2107-478b-4e92-b187-c72e2ea71ad5"
authors = ["Eric S. Tellez <donsadit@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
